### ISSUE TITLE
Any solutions for fftw3f on mac 10.13.1

### ISSUE THREAD

**Issue by vtiwari-ring** [miek/inspectrum#136]
Though I've installed fftw3f on my mac, I'm not able to build inspectrum from source. Here is the error, 

`MacBook-Pro:build vtiwari$ CMAKE_PREFIX_PATH=$(brew --prefix qt5)/lib/cmake cmake .. -DCMAKE_CXX_FLAGS:STRING=-I/usr/local/opt/qt5/include ..
-- Checking for module 'fftw3f'
--   No package 'fftw3f' found
CMake Error at /usr/local/Cellar/cmake/3.9.6/share/cmake/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.6/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:58 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/Users/vtiwari/tools/inspectrum/build/CMakeFiles/CMakeOutput.log".
MacBook-Pro:build vtiwari$`

**Comment by miek** [comment]
The CMake configuration for FFTW was cleaned up in #137, so it might be worth trying again now that is merged.

Otherwise, I'm not really sure, I do all my dev on linux so I don't know much about the mac build. You may get some clues by looking at the [travis config](https://github.com/miek/inspectrum/blob/master/.travis.yml) and [build output](https://travis-ci.org/miek/inspectrum/jobs/306453746).

If anyone who knows this better wants to chime in, feel free.
