### ISSUE TITLE
Question: Vertical/horizontal

### ISSUE THREAD

**Issue by theforcedk** [miek/inspectrum#73]
Hi there

All the tutorials/guides display the data vertical, but when I import my file from hackrf_transfer (hackrf_transfer -r 27165000.s8 -g 16 -l 32 -f 27165000), and converted via. sox (sox -t s8 27165000.s8 -t f32 out.cfile) data is being displayed horizontally - is this intentional/why does it do that? :)

<img width="1272" alt="screen shot 2016-05-29 at 21 13 18" src="https://cloud.githubusercontent.com/assets/465579/15635581/61b150b6-25e2-11e6-949c-4765dfa6050f.png">

**Comment by miek** [comment]
It's a fairly recent change: the current stable release has time on the vertical axis, but the git master has time on the horizontal axis.
I changed it mainly because I'm adding additional time-domain plots that I want to display alongside the spectrogram, and it makes a lot more sense to display them with time on the horizontal axis. Also I think it fits better on a wide-screen which most people have.

**Comment by theforcedk** [comment]
@miek Great; I like it better this way too. Was just confused as most of the guides was displaying vertically :) thanks
